runners:
  linux-amd64:
    cpu: 8
    platform: linux
    family: [c7i-flex]
    image: ubuntu22-full-x64

  linux-arm64:
    cpu: 8
    platform: linux
    family: [c7g]
    image: ubuntu22-full-arm64
