x-defaults: &defaults
  restart: unless-stopped
  init: true
  networks:
    - network

  environment: &environment
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST: postgres

  logging:
    driver: 'json-file'
    options:
      max-size: '5m'
      max-file: '10'
      tag: '{{.Name}}'

name: oracle

networks:
  network:

volumes:
  postgres:

services:
  postgres:
    <<: *defaults
    image: postgres:16.0-alpine
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432
  
  pythia:
    <<: *defaults
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *environment
      RUST_LOG: info
      ORACLE_SECRET_KEY: d0a26c65de0b4b853432c3931ee280f67b9c52de33e1b3aecb04edc1ec40ef4a
    ports:
      - 8000:8000
