x-defaults: &defaults
  restart: unless-stopped
  init: true
  networks:
    - network

  environment: &environment
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432

  logging: &logging
    driver: 'json-file'
    options:
      max-size: '5m'
      max-file: '10'
      tag: '{{.Name}}'

name: pythia

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.83.0.0/24

volumes:
  postgres:

services:
  postgres:
    <<: *defaults
    image: postgres:15.4-alpine
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'nc', '-zv', 'localhost', '5432']
      interval: 15s
      timeout: 7s
      retries: 3
      start_period: 15s
  
  pythia:
    <<: *defaults
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

