[package]
name = "pythia"
version = "0.0.1"
edition = "2021"

[dependencies]
actix = "0.13.1"
actix-cors = "0.7.0"
actix-web = "4.8.0"
actix-ws = "0.3.0"
arrayvec = { version = "0.7.6", features = ["serde"] }
atomic-take = "1.1.0"
awc = { version = "3.7.0", features = ["rustls"] }
bitcoin_hashes = "0.14.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.3.8", features = ["derive"] }
cron = { version = "0.15.0", features = ["serde"] }
displaydoc = "0.2.5"
env_logger = "0.10.2"
futures = "0.3.31"
futures-buffered = "0.2.11"
hex = { version = "0.4.3", features = ["serde"] }
humantime = "2.1.0"
json-rpc-types = "1.3.4"
log = "0.4.20"
secp256k1-zkp = { version = "0.11.0", features = [
    "serde",
    "rand-std",
    "hashes",
] }
secp256k1-zkp-sys = { version = "0.10.1", default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sqlx = { version = "0.8.3", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "macros",
    "migrate",
], default-features = false }
thiserror = "2.0.12"
tokio = { version = "1.35.1", features = [
    "time",
    "macros",
], default-features = false }

[dev-dependencies]
actix-test = "0.1.5"
actix-codec = "0.5.2"
dlc = { git = "https://github.com/p2pderivatives/rust-dlc.git" }
dlc-messages = { git = "https://github.com/p2pderivatives/rust-dlc.git", branch = "master", features = [
    "use-serde",
    "serde",
] }
futures-util = "0.3.31"
lightning = "0.0.125"
serial_test = "3.2.0"
strum = { version = "0.25.0", features = ["strum_macros", "derive"] }
