name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

env:
  SQLX_OFFLINE: 'true'

jobs:
  build:
    name: build
    runs-on: 'self-hosted'
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.70.0

      - run: sudo apt install -y pkg-config make g++ libssl-dev

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release
