name: lint

on:
  push:
    paths:
      - '**.rs'
  pull_request:
    paths:
      - '**.rs'

env:
  SQLX_OFFLINE: 'true'

jobs:
  lint:
    name: lint
    runs-on: 'self-hosted'
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: clippy, rustfmt

      - run: cargo fmt -- --check

      - run: cargo check

      - run: cargo clippy
