name: lint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: 'self-hosted'
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.72.0
        with:
          components: clippy, rustfmt

      - run: cargo fmt -- --check

      - run: cargo check

      - run: cargo clippy
