name: lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - src/**
      - .github/workflows/lint.yaml
  workflow_dispatch:
  workflow_call:

env:
  SQLX_OFFLINE: 'true'

jobs:
  lint:
    runs-on: [self-hosted, linux, 'x64']
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install -y pkg-config make g++ libssl-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
  
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy
