name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [edited, dismissed]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
