name: Rust

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write
  actions: write

env:
  SQLX_OFFLINE: 'true'
  PROJECT: dlc-markets
  NAME: pythia

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt --all -- --check

      - run: cargo clippy

  # https://docs.docker.com/build/ci/github-actions/multi-platform/
  # https://github.com/crazy-max/docker-osxcross/blob/main/.github/workflows/build.yml
  prepare:
    runs-on: [runs-on, runner=2cpu-linux-arm64]
    needs: check
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1

      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
        with:
          registries: 820242904191

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: | 
            ${{ steps.ecr.outputs.registry }}/dlc-markets/pythia
            ghcr.io/dlc-markets/pythia
          tags: |
            type=ref,event=pr
            type=sha,format=long,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
      
      - run: mv ${{ steps.meta.outputs.bake-file }} /tmp/bake-meta.json
      
      - uses: actions/upload-artifact@v4
        with:
          name: bake-meta
          path: /tmp/bake-meta.json
          if-no-files-found: error
          retention-days: 1

  bake:
    runs-on: 
      - runs-on
      - runner=${{ matrix.platform }}
      - run-id=${{ github.run_id }}
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        platform: [linux-amd64, linux-arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: bake-meta
          path: /tmp

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
  
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
        with:
          registries: 820242904191

      - uses: docker/bake-action@v5
        id: bake
        with:
          files: |
            ./docker-bake.hcl
            /tmp/bake-meta.json
          targets: ci
          set: |
            *.tags=
            *.output=type=image,"name=${{ steps.ecr.outputs.registry }}/dlc-markets/pythia,ghcr.io/dlc-markets/pythia",push-by-digest=true,name-canonical=true,push=true
            *.cache-from=type=registry,ref=${{ steps.ecr.outputs.registry }}/dlc-markets/pythia:cache${{ matrix.platform }}
            *.cache-to=type=registry,image-manifest=true,oci-mediatypes=true,mode=max,ref=${{ steps.ecr.outputs.registry }}/dlc-markets/pythia:cache-${{ matrix.platform }}

      # Github actions does not support matrix outputs
      # https://github.com/actions/runner/pull/2477
      - run: |
          mkdir -p /tmp/digests
          digest="${{ fromJSON(steps.bake.outputs.metadata).ci['containerimage.digest'] }}"
          touch "/tmp/digests/${digest#sha256:}"
          ls -la /tmp/digests

      - uses: actions/upload-artifact@v4
        with:
          name: digests-${{ github.run_id }}-${{ matrix.platform }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: [runs-on, runner=2cpu-linux-arm64]
    needs: bake
    steps:
      - uses: actions/checkout@v4

      # Sometimes there is still files here on self-hosted runners
      - run: rm -rf /tmp/digests/*

      - uses: actions/download-artifact@v4
        with:
          name: bake-meta
          path: /tmp
      
      - uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ github.run_id }}-*
          merge-multiple: true
      
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1

      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
        with:
          registries: 820242904191

      - run: ./scripts/merge-images.sh
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}

      - run: ./scripts/merge-images.sh
        env:
          REGISTRY: ghcr.io
